app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager,admin
from datetime import datetime
from flask_admin.contrib.sqla import ModelView

class Writer(UserMixin,db.Model):
    __tablename__='writers'
    id =db.Column(db.Integer,primary_key =True)
    username =db.Column(db.String(255))
    email=db.Column(db.String(255),unique =True,index=True)
    pass_secure=db.Column(db.String(255))
    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')
    @password.setter
    def password(self,password):
        self.pass_secure=generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)
    def __repr__(self):
        return f'User {self.username}'
    '''
    this retrieves a user when a unique identifier is passed in this cause we pass in the id
    '''
    @login_manager.user_loader
    def load_user(user_id):
        return Writer.query.get(int(user_id))
class Subscribe(db.Model):
    __tablename__='subscribe'
    id=db.Column(db.Integer,primary_key=True)
    username=db.Column(db.String(255))
    email=db.Column(db.String(255),unique=True,index=True)
    def __repr__(self):
        return f'User {self.username}'
class Post(db.Model):
    __tablename__='posts'
    id=db.Column(db.Integer,primary_key =True)
    username=db.Column(db.String(255))
    post_title=db.Column(db.String(255))
    post_date=db.Column(db.DateTime,default=datetime.utcnow)
    post=db.Column(db.String)
    profile_pic_path = db.Column(db.String())
    comments=db.relationship('Comments',backref='post',lazy='dynamic')
    def __repr__(self):
        return f'Post{self.post_title}'
class Comments(db.Model):
    __tablename__='comments'
    id=db.Column(db.Integer,primary_key=True)
    username=db.Column(db.String(255))
    comment=db.Column(db.String)
    post_id =db.Column(db.Integer,db.ForeignKey('posts.id'))
    def __repr__(self):
        return f'User {self.username}'
    '''
    adding model views allows you to manage the models you have in the database
    '''
admin.add_view(ModelView(Writer, db.session))
admin.add_view(ModelView(Post, db.session))
admin.add_view(ModelView(Comments,db.session))
admin.add_view(ModelView(Subscribe,db.session))

app/main/forms.py
from  flask_wtf import FlaskForm
from ..models import Subscribe
from wtforms import ValidationError
from  wtforms.validators import Required,Email
from wtforms import StringField,PasswordField,SubmitField,BooleanField,DateField,TextAreaField


class Subscribe_form(FlaskForm):
    username = StringField('Enter your first name',validators=[Required()])
    email=StringField('Enter your email to recieve alerts ',validators=[Required(),Email()])
    submit =SubmitField('Subscribe..')
    def validate_email(self,data_field):
        if Subscribe.query.filter_by(email=data_field.data).first():
            raise ValidationError(' that email is already taken')
    def validate_name(self,data_field):
        if Subscribe.query.filter_by(username = data_field.data).first():
            raise ValidationError('that user name is already taken')
class Post_form(FlaskForm):
    username=StringField('Enter your username writer...',validators=[Required()])
    post_title=StringField('Enter the title of the post',validators=[Required()])
    post =TextAreaField('Enter your post',validators=[Required()])
    Submit=SubmitField('Submit Post')
class Comments_form(FlaskForm):
    username=StringField('Enter Your Name',validators=[Required()])
    comment=TextAreaField('Leave a comment',validators=[Required()])
    submit=SubmitField('Submit comment')

app/__init__.py
from flask import Flask
from config import config_options
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_mail import Mail
from flask_admin import Admin
from flask_admin.contrib.sqla import ModelView
from flask_uploads import UploadSet,configure_uploads,IMAGES

bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager =LoginManager()
login_manager.session_protection='strong'
login_manager.login_view='auth.login'
mail=Mail()
admin=Admin()
photos =UploadSet('photos',IMAGES)
def create_app(config_state):
    app = Flask(__name__)
    app.config.from_object(config_options[config_state])
    configure_uploads(app,photos)

    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    admin.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)

from . import views,forms

app/main/views.py
from flask import render_template,request,redirect,url_for
from . import main
from flask_login import login_required,current_user
from ..email import mail_message
from ..models import Subscribe,Post,Comments
from .forms import Subscribe_form,Post_form,Comments_form
from .. import db,photos,SQLAlchemy
from flask import flash
# Views
@main.route('/',methods = ["GET","POST"])
def index():

    form = Subscribe_form()

    if form.validate_on_submit():
        subscriber=Subscribe(email =form.email.data,username=form.username.data)
        db.session.add(subscriber)
        db.session.commit()
        mail_message("Welcome to the Zhaviah Trend's blog","email/welcome_user",subscriber.email,subscriber=subscriber)

        flash("Welcome new subscriber")
        return redirect(url_for('main.index'))
    posts=Post.query.all()

    return render_template('index.html',subscribe_form = form,posts=posts)

@main.route('/writers',methods=["GET","POST"])
@login_required

def writers():
    form =Post_form()

    if form.validate_on_submit():
        posts=Post(username=form.username.data,post_title=form.post_title.data,post=form.post.data)
        db.session.add(posts)
        db.session.commit()

        flash("succefully published")
        return redirect(url_for('main.index'))
    post=Post.query.all()
    if 'photo' in request.files:
        filename=photos.save(request.files['photo'])
        path=f'photos/{filename}'
        post.profile_pic_path=path
        db.session.commit()
    return render_template('write.html',post_form=form)
@main.route('/blogs/<int:id>',methods=["GET","POST"])
def blogs(id):
    form=Comments_form()
    posts=Post.query.filter_by(id=id).first()


    if form.validate_on_submit():
        comments=Comments(username=form.username.data,comment=form.comment.data,post_id=id)
        db.session.add(comments)
        db.session.commit()
        flash("comment added")
        return redirect(url_for('main.index'))

    comments=Comments.query.filter_by(post_id=id).all()



    return render_template("blogs/blog.html",posts=posts,comments_form=form,comments=comments)
@main.route('/admin',methods=["GET","POST"])
@login_required

def admin():
    return render_template("admin/index.html")

app/templates/base.html
{% extends 'bootstrap/base.html'%}
{% block navbar %}
 {% include 'navbar.html' %}
 {%include 'footer.html' %}
{% endblock %}

app/templates/blogs/blog.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% import 'macros.html' as macro %}

{% block content %}
<div class ="container">
  <div class="row">
    <div class="col-md-8">

  <h2 style="font-family: 'Playfair Display', serif;"><b> Title:</b> {{posts.post_title}}</h2>
  <h3 style="font-family: 'Playfair Display', serif;"><b>Author:</b> {{posts.username}}</h3>
  <p style="font-family: 'Playfair Display', serif;"><b>Blog Post:</b> {{posts.post}}</p>
  <p style="font-family: 'Playfair Display', serif;"><b>Date:</b> {{posts.post_date}}</p>

  <h3 style="font-family: 'Playfair Display', serif;">Comments</h3>
  {{macro.displayComments(comments)}}
 </div>
 <div class="col-md-4">
   <div class="alert alert-success" role="alert">
   {{wtf.quick_form(comments_form)}}
 </div>
 </div>
</div>
</div>
{% endblock %}

app/templates/footer.html
<nav class="navbar-wrapper navbar-inverse navbar-fixed-bottom">
    <div class="container-fluid">
      <p class="navbar-text pull-left">&copy; 2018 by Personal blog. All rights reserved.</p>
      <a href="#" class="btn navbar-btn btn-danger pull-right">Subscribe</a>
    </div>
  </nav>
  

app/templates/index.html
{% import 'macros.html' as macro %}
{% import 'bootstrap/wtf.html' as wtf %}
{% extends 'base.html' %}
{% block styles %}
{{ super () }}

 <link href="https://fonts.googleapis.com/css?family=Playfair+Display" rel="stylesheet">
{% endblock %}

{% block content %}


<div class="container">
<div class="row">
<ul>
  {{macro.displayPost(posts)}}

</ul>
</div>
</div>




  <div class="container">


      <div class="row">
   <div class="col-md-4"> </div>
     <div class="col-md-8">
     <div class="alert alert-info">
  {{wtf.quick_form(subscribe_form)}}

    </div>
  </div>
</div>
</div>
{% endblock %}

app/templates/macros.html
{% macro displayPost(post_list) %}
  {% for post in post_list %}


  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      {%if post.profile_pic_path %}
      <img src="{{url_for('static',filename=post.profile_pic_path)}}" alt="..."><br>
      {%else%}
      <p>no profile</p>
      {% endif %}
      <hr>
      <div class="caption">
      <h3 style="font-family: 'Playfair Display', serif;"><a href="/blogs/{{post.id}}"style="color:black;">Title:{{post.post_title}}</a></h3>
      <p style="font-family: 'Playfair Display', serif;"><b>Description:</b>{{post.post |truncate(100)}}</p>
      </div>
    </div>
    <br>
  </div>




  {% endfor %}
  {% endmacro %}

  {% macro displayComments(comments_list) %}
  {% for comment in comments_list %}
  <div class="alert alert-warning">
    <nav aria-label="...">
  <ul class="pager">
    <li class="previous disabled"><a href="#"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> {{comment.username}}</a></li>
  </ul>
</nav>
    <p style="font-family: 'Playfair Display', serif;">{{comment.comment}}<p>
  </div>
    {% endfor %}
    {% endmacro %}

app/templates/navbar.html
<div class="container-fluid">
    <div class="navbar navbar-inverse" role="navigation"  style="background-image:url(../static/photos/back.jpg); height:500px;background-position:0% 25%;background-size: cover;">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                      <span class="sr-only">Toggle navigation</span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/" style="color:white"> Personal Blog </a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="/" style="color:white">Home</a></li>
                      </ul>
                        <ul class="nav navbar-nav navbar-right">
                          {% if current_user.is_authenticated %}
                          <li style="color:white;">{{current_user.username}}</li>
                          <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                          {% else %}
                          <li><a href="{{url_for('auth.login')}}"><span class="glyphicon glyphicon-star" aria-hidden="true"></span>Sign in Admin</a></li>
                          {%endif%}
                        </ul>
                </div>
    
            </div>
            <h1 style="font-family: 'Playfair Display', serif;color:white; text-align:center"><b>Hello welcome to the Personal Blog </b></h1>
            <h2 style="font-family: 'Playfair Display', serif; color:white; text-align:center" >The blog that allows you to comment on various posts</h2>
        </div>
    
      </div>
    

app/templates/write.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<h1>Welcome writer</h1>
<div class="container">

  <div class="jumbotron">
    <div class="row">
 <div class="col-md-4"> </div>
   <div class="col-md-8">

{{wtf.quick_form(post_form)}}
<form  action="{{url_for('main.writers')}}" method="post" enctype = "multipart/form-data">

      <input type="file"  name="photo" class="form-control" required>
      <input type="submit">

  </div>
</div>
</div>
</div>

{% endblock %}